# Generated by Django 2.2.2 on 2019-07-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_person_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='person',
        ),
        migrations.AddField(
            model_name='work',
            name='work_detail',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='unit',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateTimeField(auto_now=True)),
                ('unit', models.IntegerField(default=0)),
                ('salary_today', models.FloatField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.Person')),
            ],
        ),
    ]
