# Generated by Django 2.2.2 on 2019-07-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_auto_20190711_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='work_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salary.Work'),
            preserve_default=False,
        ),
    ]
